### ISSUE TITLE
Create Air One processing code

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/OIF-Pipeline-Logic#6]
- [x] validate
- [x] schemas
- [x] transform
- [x] enrich

**Comment by EFT-Defra** [comment]
# TODO

- [ ] Add module docstring to src/oiflib/air/one/schema.py
- [ ] Add module docstring to src/oiflib/air/one/enrich.py
- [ ] Add function docstrings to src/oiflib/air/one/enrich.py
- [ ] Add function docstrings to tests/air/one/test_enrich.py
